version: '2.2'

services:
    mongodb:
        image: mongo:3.4
        expose:
            - 27017
#        ports:
#            - "127.0.0.1:27017:27017"
        volumes:
            - ./mongodb-data:/data/db
        restart: unless-stopped

    research:
        image: rc-ftgm:1.1
        ports:
            - "8083:8083"
        volumes:
            - './log:/log'
            - './research-health-data:/research-health-data'
        command: java -jar /research-centre.jar